name: EAS Build

on: 
  pull_request:
    branches:
      - main
    types: 
      - closed

jobs:
  build:
    if: github.event.pull_request.merged == true
    name: Build Android App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EAS_EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Get configs
        env:
          GOOGLE_SERVICES_64: ${{ secrets.EAS_GOOGLE_PLAY_API }}
        run:  |
          echo $GOOGLE_SERVICES_64 > google-services.json.64
          base64 -d -i google-services.json.64 > google-services.json

      - name: Build and Submit
        run: eas build --platform android --profile production --non-interactive --auto-submit-with-profile=preview --no-wait